// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "tsx prisma/seed.ts",
  },
  // Prisma 7 removed url/directUrl from schema.prisma entirely — Migrate
  // and other CLI commands now take their connection from here instead.
  // This must be the DIRECT (unpooled) connection: Supabase's Transaction
  // Pooler doesn't support the session-level features (e.g. advisory
  // locks) that schema migrations need. The running app is unaffected —
  // it connects via the adapter in lib/prisma.ts, which uses the pooled
  // DATABASE_URL.
  datasource: {
    url: process.env["DIRECT_URL"],
  },
});
